matrix:
    include:
        - os: linux
          language: python
          python: 2.7
          env: PYTHONVER=2.7

        - os: linux
          language: python
          python: 3.5
          env: PYTHONVER=3.5

        - os: linux
          language: python
          python: 3.6
          env: PYTHONVER=3.6

#       - os: osx
#         language: generic
#         env: PYTHONVER=3.6

# There are a lot of requirements here because we do coverage, testing, reporting, doc building
install:
    - if [[ $TRAVIS_OS_NAME == "osx" ]]; then
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
      else
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi;
      echo "DONE"
    - bash miniconda.sh -b -p $HOME/miniconda
    - export NUMBA_DISABLE_JIT=1    # For coverage report
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda config --set always_yes yes --set changeps1 no
    - conda create -n test python=$PYTHONVER
    - source activate test
    - conda update -q --all
    - conda install -q -c conda-forge six numpy numba sphinx sphinx_rtd_theme ply pandoc pypandoc pytest pytest-cov coverage coveralls
    - pip install travis-sphinx codacy-coverage
    - pip install .

script:
    - pytest --cov;
    - if [[ $TRAVIS_OS_NAME == "linux" ]] && [[ $PYTHONVER == 3.6 ]]; then
#         coverage xml;
          coverage run --source=exa setup.py test;
          travis-sphinx build;
      fi

after_success:
    - if [[ $TRAVIS_OS_NAME == "linux" ]] && [[ $PYTHONVER == 3.6 ]]; then
          coveralls;
          python-codacy-coverage -r coverage.xml;
          travis-sphinx deploy;
      fi
